// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\Tutorials\Tut05_Textures\resource.rdf

#define resource_NUM_RESOURCES 1UL

#define resource_Banana_OFFSET 0UL
