// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\SkyBox\resource.rdf

#define resource_NUM_RESOURCES 2UL

#define resource_SkyBoxColorLookupTable_OFFSET 80UL
#define resource_SkyBoxLuminanceCubeMap_OFFSET 100UL
