// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\VolumeFog\Resource.rdf

#define Resource_NUM_RESOURCES 8UL

#define Resource_Treebark_OFFSET 176UL
#define Resource_VolGroun_OFFSET 196UL
#define Resource_SkyBoxXN_OFFSET 216UL
#define Resource_SkyBoxXP_OFFSET 236UL
#define Resource_SkyBoxYN_OFFSET 256UL
#define Resource_SkyBoxYP_OFFSET 276UL
#define Resource_SkyBoxZN_OFFSET 296UL
#define Resource_SkyBoxZP_OFFSET 316UL
