// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\Fire\Resource.rdf

#define Resource_NUM_RESOURCES 10UL

#define Resource_SkyBoxXN_OFFSET 224UL
#define Resource_SkyBoxXP_OFFSET 244UL
#define Resource_SkyBoxYN_OFFSET 264UL
#define Resource_SkyBoxYP_OFFSET 284UL
#define Resource_SkyBoxZN_OFFSET 304UL
#define Resource_SkyBoxZP_OFFSET 324UL
#define Resource_Fireground_OFFSET 344UL
#define Resource_FlameColor_OFFSET 364UL
#define Resource_FireNoise_OFFSET 384UL
#define Resource_NoiseAlpha_OFFSET 404UL
