// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\PolynomialTextureMaps\Resource.rdf

#define Resource_NUM_RESOURCES 3UL

#define Resource_MoonPoly1_OFFSET 64UL
#define Resource_MoonPoly2_OFFSET 84UL
#define Resource_MoonColor_OFFSET 104UL
