// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\PixelShader\resource.rdf

#define resource_NUM_RESOURCES 3UL

#define resource_Texture0_OFFSET 64UL
#define resource_Texture1_OFFSET 84UL
#define resource_Checker_OFFSET 104UL
