// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\VolumeSprites\resource.rdf

#define resource_NUM_RESOURCES 3UL

#define resource_Ground2_OFFSET 0UL
#define resource_Particle_OFFSET 20UL
#define resource_ParticleVolume_OFFSET 40UL
