// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Networking\UIXAuth\Font_kor.rdf

#define Font_kor_NUM_RESOURCES 2UL

#define Font_kor_Font_OFFSET 0UL
#define Font_kor_FontData_OFFSET 20UL
