// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\FocusBlur\resource.rdf

#define resource_NUM_RESOURCES 3UL

#define resource_Texture0_OFFSET 0UL
#define resource_Texture1_OFFSET 20UL
#define resource_Checker_OFFSET 40UL
