// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\MatrixPaletteSkinning\Resource.rdf

#define Resource_NUM_RESOURCES 6UL

#define Resource_M0CM0_OFFSET 128UL
#define Resource_M0BM0_OFFSET 148UL
#define Resource_M1CM0_OFFSET 168UL
#define Resource_M1BM0_OFFSET 188UL
#define Resource_M2CM0_OFFSET 208UL
#define Resource_M2BM0_OFFSET 228UL
