// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\ReferenceUI\VirtualKeyboard\ControllerS.rdf

#define ControllerS_NUM_RESOURCES 1UL

#define ControllerS_ControllerSTexture_OFFSET 0UL
