// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\ReferenceUI\VirtualKeyboard\resource.rdf

#define resource_NUM_RESOURCES 1UL

#define resource_KeyboardKey_OFFSET 0UL
