// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\ReferenceUI\VirtualKeyboard\Xboxdings_24.rdf

#define Xboxdings_24_NUM_RESOURCES 2UL

#define Xboxdings_24_Font_OFFSET 0UL
#define Xboxdings_24_FontData_OFFSET 20UL
