// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Certification\TechCertGame\font16.rdf

#define font16_NUM_RESOURCES 2UL

#define font16_Font_OFFSET 0UL
#define font16_FontData_OFFSET 20UL
