// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Certification\TechCertGame\font.rdf

#define font_NUM_RESOURCES 2UL

#define font_Font_OFFSET 0UL
#define font_FontData_OFFSET 20UL
