// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Certification\TechCertGame\MenuResource.rdf

#define MenuResource_NUM_RESOURCES 1UL

#define MenuResource_MenuSelect_OFFSET 0UL
