// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\PointSprites\resource.rdf

#define resource_NUM_RESOURCES 2UL

#define resource_Ground2_OFFSET 0UL
#define resource_Particle_OFFSET 20UL
