// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\BumpMapping\DotProduct3\resource.rdf

#define resource_NUM_RESOURCES 2UL

#define resource_Wood_OFFSET 48UL
#define resource_FaceNormalMap_OFFSET 68UL
