// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\AlphaFog\Resource.rdf

#define Resource_NUM_RESOURCES 7UL

#define Resource_Seafloor_OFFSET 160UL
#define Resource_SkyBoxXN_OFFSET 180UL
#define Resource_SkyBoxXP_OFFSET 200UL
#define Resource_SkyBoxYN_OFFSET 220UL
#define Resource_SkyBoxYP_OFFSET 240UL
#define Resource_SkyBoxZN_OFFSET 260UL
#define Resource_SkyBoxZP_OFFSET 280UL
