// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\ReferenceUI\LoadSave\LoadSaveResource.rdf

#define LoadSaveResource_NUM_RESOURCES 11UL

#define LoadSaveResource_Background_OFFSET 176UL
#define LoadSaveResource_PlainBack_OFFSET 196UL
#define LoadSaveResource_Up_OFFSET 216UL
#define LoadSaveResource_Down_OFFSET 236UL
#define LoadSaveResource_MsgBox_OFFSET 256UL
#define LoadSaveResource_MU_OFFSET 276UL
#define LoadSaveResource_MUWide_OFFSET 296UL
#define LoadSaveResource_MU_Sel_OFFSET 316UL
#define LoadSaveResource_Xbox_OFFSET 336UL
#define LoadSaveResource_Xbox_Sel_OFFSET 356UL
#define LoadSaveResource_MU_Bad_OFFSET 376UL
