// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Input\Gamepad\Font16.rdf

#define Font16_NUM_RESOURCES 2UL

#define Font16_Font_OFFSET 0UL
#define Font16_FontData_OFFSET 20UL
