// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Networking\Marketplace\iconfont.rdf

#define iconfont_NUM_RESOURCES 2UL

#define iconfont_Font_OFFSET 0UL
#define iconfont_FontData_OFFSET 20UL
