// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Misc\TVCalibration\resource.rdf

#define resource_NUM_RESOURCES 2UL

#define resource_TestPattern_OFFSET 48UL
#define resource_Speaker_OFFSET 68UL
