// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\BumpMapping\BumpDemo\gamepad.rdf

#define gamepad_NUM_RESOURCES 1UL

#define gamepad_GamepadTexture_OFFSET 0UL
