// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\BumpMapping\BumpDemo\resource.rdf

#define resource_NUM_RESOURCES 3UL

#define resource_Lobby_OFFSET 0UL
#define resource_GearBump_OFFSET 20UL
#define resource_Gear_OFFSET 40UL
