// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\MotionBlur\Resource.rdf

#define Resource_NUM_RESOURCES 9UL

#define Resource_SkyBoxXN_OFFSET 208UL
#define Resource_SkyBoxXP_OFFSET 228UL
#define Resource_SkyBoxYN_OFFSET 248UL
#define Resource_SkyBoxYP_OFFSET 268UL
#define Resource_SkyBoxZN_OFFSET 288UL
#define Resource_SkyBoxZP_OFFSET 308UL
#define Resource_SphereTexture_OFFSET 328UL
#define Resource_BiHull_OFFSET 348UL
#define Resource_Wings_OFFSET 368UL
