// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\NormalMapGeneration\resource.rdf

#define resource_NUM_RESOURCES 1UL

#define resource_NormalMap_OFFSET 32UL
