// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\MirrorClip\Resource.rdf

#define Resource_NUM_RESOURCES 6UL

#define Resource_Ceiling_OFFSET 144UL
#define Resource_Floor_OFFSET 164UL
#define Resource_EastWall_OFFSET 184UL
#define Resource_WestWall_OFFSET 204UL
#define Resource_NorthWall_OFFSET 224UL
#define Resource_SouthWall_OFFSET 244UL
