// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\HeatShimmer\Resource.rdf

#define Resource_NUM_RESOURCES 13UL

#define Resource_Shimmer0_OFFSET 304UL
#define Resource_Shimmer1_OFFSET 324UL
#define Resource_Shimmer2_OFFSET 344UL
#define Resource_DesertSky_front_OFFSET 364UL
#define Resource_DesertSky_back_OFFSET 384UL
#define Resource_DesertSky_left_OFFSET 404UL
#define Resource_DesertSky_right_OFFSET 424UL
#define Resource_DesertSky_up_OFFSET 444UL
#define Resource_Cactus_OFFSET 464UL
#define Resource_Clump_OFFSET 484UL
#define Resource_Desert_Color_OFFSET 504UL
#define Resource_Rock_OFFSET 524UL
#define Resource_Tower_OFFSET 544UL
