// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Sound\SpeechRecognition\font_jp.rdf

#define font_jp_NUM_RESOURCES 2UL

#define font_jp_Font_OFFSET 0UL
#define font_jp_FontData_OFFSET 20UL
