// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\FresnelReflect\resource.rdf

#define resource_NUM_RESOURCES 4UL

#define resource_Scene_OFFSET 80UL
#define resource_Scene1_OFFSET 100UL
#define resource_Earth_OFFSET 120UL
#define resource_Clouds_OFFSET 140UL
