// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Networking\UIXKeyboard\Font18.rdf

#define Font18_NUM_RESOURCES 2UL

#define Font18_Font_OFFSET 0UL
#define Font18_FontData_OFFSET 20UL
