// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Storage\FastLoad\Resource1.rdf

#define Resource1_NUM_RESOURCES 11UL

#define Resource1_T0_OFFSET 144UL
#define Resource1_T1_OFFSET 164UL
#define Resource1_T2_OFFSET 184UL
#define Resource1_T3_OFFSET 204UL
#define Resource1_T4_OFFSET 224UL
#define Resource1_T5_OFFSET 244UL
#define Resource1_T6_OFFSET 264UL
#define Resource1_T7_OFFSET 284UL
#define Resource1_T8_OFFSET 304UL
#define Resource1_T9_OFFSET 324UL
#define Resource1_QuadsVB_OFFSET 344UL
