// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Storage\FastLoad\Resource0.rdf

#define Resource0_NUM_RESOURCES 11UL

#define Resource0_T0_OFFSET 144UL
#define Resource0_T1_OFFSET 164UL
#define Resource0_T2_OFFSET 184UL
#define Resource0_T3_OFFSET 204UL
#define Resource0_T4_OFFSET 224UL
#define Resource0_T5_OFFSET 244UL
#define Resource0_T6_OFFSET 264UL
#define Resource0_T7_OFFSET 284UL
#define Resource0_T8_OFFSET 304UL
#define Resource0_T9_OFFSET 324UL
#define Resource0_QuadsVB_OFFSET 344UL
