// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\BumpMapping\HighQualityBumpMapping\resource.rdf

#define resource_NUM_RESOURCES 2UL

#define resource_Flat_OFFSET 48UL
#define resource_BumpMap_OFFSET 68UL
