// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\AntiAlias\resource.rdf

#define resource_NUM_RESOURCES 2UL

#define resource_Scene_OFFSET 48UL
#define resource_SphereMap_OFFSET 68UL
