// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\VertexShader\FastVSConstants\resource.rdf

#define resource_NUM_RESOURCES 1UL

#define resource_DefaultTexture_OFFSET 0UL
