// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\Glass\resource.rdf

#define resource_NUM_RESOURCES 7UL

#define resource_EnvMap_OFFSET 144UL
#define resource_LobbyXP_OFFSET 164UL
#define resource_LobbyXN_OFFSET 184UL
#define resource_LobbyYP_OFFSET 204UL
#define resource_LobbyYN_OFFSET 224UL
#define resource_LobbyZP_OFFSET 244UL
#define resource_LobbyZN_OFFSET 264UL
