// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Misc\FastCPU\consolefont.rdf

#define consolefont_NUM_RESOURCES 2UL

#define consolefont_Font_OFFSET 0UL
#define consolefont_FontData_OFFSET 20UL
