// Automatically generated by the bundler tool from D:\Git\RXDK-VS20XX\XDKSamples\Graphics\ShadowBuffer\resource.rdf

#define resource_NUM_RESOURCES 3UL

#define resource_Floor_OFFSET 64UL
#define resource_Wings_OFFSET 84UL
#define resource_BiHull_OFFSET 104UL
